display_name = "Akanda"
library_name = "akanda"
version = "0.1.0"
author = "Duncan McGreggor"
author_email = "dev-community@dreamhost.com"
license = "BSD"
url = "http://github.com/dreamhost/akanda"
description = "Akanda Appliance"
long_description = "A packet filter appliance for OpenStack deployments."
# Note that custom requirements from unreleased software (e.g., git URLs) can
# be put here, since setup.py can't handle them. They are instead added to the
# requirements.txt file, generated by the function below.
requires = [
    "coverage",
    "pep8",
    "pyflakes",
    "mock>=0.8.0",
    "repoze.lru==0.5",
    "wsgiref==0.1.2",
    "netaddr>=0.7.7",
    "flask>=0.9",
    ]


def generate_requirements(full_path):
    """
    This function is called by one or more make targets to process the full
    suite of dependencies for Akanda.
    """
    with open(full_path, "w") as file:
        # until the next verion of nosetests is released, we need master for
        # coverage support
        deps = requires +[
            "https://github.com/nose-devs/nose/zipball/master",
            # XXX once we have horizon unit tests in place, we'll need the
            # following:
            #"https://github.com/openstack/horizon/zipball/master",
            # XXX once we convert to using PyPF, we'll need the following:
            #"https://github.com/dreamhost/pypf/zipball/master",
            ]
        for dep in deps:
            file.write(dep + "\n")
